#
# Vivado (TM) v2014.2 (64-bit)
#
# caribou_test.tcl: Tcl script for re-creating project 'caribou_test'
#
# Generated by Vivado on Fri Oct 23 09:33:53 -0400 2015
# IP Build 924643 on Fri May 30 09:20:16 MDT 2014
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (caribou_test.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/xlx_k7v7_gbt_bank_package.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/xlx_k7v7_gbt_banks_user_setup.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_bank_package.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_tx/tx_dpram/xlx_k7v7_tx_dpram.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_tx/tx_dpram/xlx_k7v7_tx_dpram.ngc"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/rx_dpram/xlx_k7v7_rx_dpram.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/rx_dpram/xlx_k7v7_rx_dpram.ngc"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_elpeval.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_sync_pulse.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_sync_block.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_tx/xlx_k7v7_gbt_tx_gearbox_std_dpram.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_tx/gbt_tx_gearbox_std_rdwrctrl.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_polydiv.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/xlx_k7v7_gbt_rx_gearbox_std_dpram.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_gearbox_std_rdctrl.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_syndrom.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_rs2errcor.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_lmbddet.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_errlcpoly.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_chnsrch.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_tx_startup_fsm.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_tx_manual_phase_align.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_std.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_rx_startup_fsm.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_rx_manual_phase_align.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_latopt.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_auto_phase_align.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/mgt/mgt_latopt_bitslipctrl.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_tx/gbt_tx_scrambler_21bit.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_tx/gbt_tx_scrambler_16bit.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_tx/gbt_tx_gearbox_std.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_tx/gbt_tx_gearbox_latopt.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_rsencode.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_intlver.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_gearbox_std.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_gearbox_latopt.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_framealigner_wraddr.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_framealigner_rightshift.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_framealigner_pattsearch.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_framealigner_bscounter.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_descrambler_21bit.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_descrambler_16bit.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_rsdec.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_deintlver.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/mgt/xlx_k7v7_mgt_std.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/mgt/xlx_k7v7_mgt_latopt.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_tx/gbt_tx_scrambler.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_tx/gbt_tx_gearbox.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_tx/gbt_tx_encoder.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_status.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_gearbox.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_framealigner.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_descrambler.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/xlx_k7v7_gbt_rx_frameclk_phalgnr_ctrl.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/mgt/multi_gigabit_transceivers.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_tx/gbt_tx.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_rx/gbt_rx.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/gbt_rx_frameclk_phalgnr.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/gbt_pattern_matchflag.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/gbt_pattern_generator.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/gbt_pattern_checker.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/gbt_bank_reset.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/tx_pll/xlx_k7v7_tx_pll.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/gbt_bank.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/fei4/8b10_dec.vhd"
#    "C:/Hongbin/ZC706_Projects/caribou_test/caribou_test.srcs/sources_1/bd/ps7/ps7.bd"
#    "C:/Hongbin/ITK/firmware_git/source/tlu/tlu_master.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/iic/iic_master.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/fei4_fifo_wrapper.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/xlx_k7v7_reset.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/core_sources/xlx_k7v7_gbt_example_design.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/fei4/idelay2.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/fei4/idelay.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/fei4/fei4_dat_deser.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/fei4/fei4_data_extract.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/ccpd/pulse_gen_core.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/ccpd/ccpd_cfg_core.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/adc/freq_counter.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/adc/adc_lvds_receiver.vhd"
#    "C:/Hongbin/ZC706_Projects/caribou_test/caribou_test.srcs/sources_1/new/fei4_rx2.vhd"
#    "C:/Hongbin/ZC706_Projects/caribou_test/caribou_test.srcs/sources_1/bd/ps7/hdl/ps7_wrapper.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/tlu/tlu_simulator_wrapper.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/ipbus/iobus.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/ipbus/axi_lite_ipif.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/iic/iic_controller.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/gbt_fpga_wrapper.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/gbt_fpga_control_link.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/gbt_fpga/fei4_gbt_interface.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/fei4/fei4_rx.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/fei4/fei4b_config.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/ccpd/pulse_gen.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/ccpd/ccpd_cfg.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/axi_hp/axi_mburst1.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/axi_hp/axi_mburst.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/axi_hp/axi_data_gen.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/adc/ads5292_lvds_receiver.vhd"
#    "C:/Hongbin/ITK/firmware_git/source/TOP.vhd"
#    "C:/Hongbin/ZC706_Projects/caribou_test/caribou_test.srcs/sources_1/imports/caribou_test/archive_project_summary.txt"
#    "C:/Hongbin/ZC706_Projects/caribou_test/caribou_test.srcs/sources_1/ip/clk_wiz_0_0/clk_wiz_0.xci"
#    "C:/Hongbin/ZC706_Projects/caribou_test/caribou_test.srcs/sources_1/ip/axi_hp_fifo_0/axi_hp_fifo.xci"
#    "C:/Hongbin/ZC706_Projects/caribou_test/caribou_test.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci"
#    "C:/Hongbin/ITK/firmware_git/source/ip/vio_0/vio_0.xci"
#    "C:/Hongbin/ITK/firmware_git/source/ip/ila_0/ila_0.xci"
#    "C:/Hongbin/ITK/firmware_git/source/ip/fei4_data_fifo/fei4_data_fifo.xci"
#    "C:/Hongbin/ITK/firmware_git/constr/phy_cons.xdc"
#    "C:/Hongbin/ZC706_Projects/caribou_test/caribou_test.srcs/sim_1/new/fei4_cfg_tb.vhd"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/../../../ZC706_Projects/caribou_test"]"

# Create project
create_project caribou_test ./caribou_test

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects caribou_test]
set_property "board_part" "xilinx.com:zc706:part0:1.0" $obj
set_property "default_lib" "xil_defaultlib" $obj
set_property "simulator_language" "Mixed" $obj
set_property "target_language" "VHDL" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../source/gbt_fpga/xlx_k7v7_gbt_bank_package.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/xlx_k7v7_gbt_banks_user_setup.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_bank_package.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/tx_dpram/xlx_k7v7_tx_dpram.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/tx_dpram/xlx_k7v7_tx_dpram.ngc"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/rx_dpram/xlx_k7v7_rx_dpram.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/rx_dpram/xlx_k7v7_rx_dpram.ngc"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_elpeval.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_sync_pulse.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_sync_block.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/xlx_k7v7_gbt_tx_gearbox_std_dpram.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_gearbox_std_rdwrctrl.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_polydiv.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/xlx_k7v7_gbt_rx_gearbox_std_dpram.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_gearbox_std_rdctrl.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_syndrom.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_rs2errcor.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_lmbddet.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_errlcpoly.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_chnsrch.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_tx_startup_fsm.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_tx_manual_phase_align.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_std.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_rx_startup_fsm.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_rx_manual_phase_align.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_latopt.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_auto_phase_align.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/mgt/mgt_latopt_bitslipctrl.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_scrambler_21bit.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_scrambler_16bit.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_gearbox_std.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_gearbox_latopt.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_rsencode.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_intlver.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_gearbox_std.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_gearbox_latopt.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_framealigner_wraddr.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_framealigner_rightshift.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_framealigner_pattsearch.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_framealigner_bscounter.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_descrambler_21bit.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_descrambler_16bit.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_rsdec.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_deintlver.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_mgt_std.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_mgt_latopt.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_scrambler.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_gearbox.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_encoder.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_status.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_gearbox.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_framealigner.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_descrambler.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/xlx_k7v7_gbt_rx_frameclk_phalgnr_ctrl.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/mgt/multi_gigabit_transceivers.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/gbt_rx_frameclk_phalgnr.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/gbt_pattern_matchflag.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/gbt_pattern_generator.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/gbt_pattern_checker.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/gbt_bank_reset.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/tx_pll/xlx_k7v7_tx_pll.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/gbt_bank.vhd"]"\
 "[file normalize "$origin_dir/../source/fei4/8b10_dec.vhd"]"\
 "[file normalize "$origin_dir/../../../ZC706_Projects/caribou_test/caribou_test.srcs/sources_1/bd/ps7/ps7.bd"]"\
 "[file normalize "$origin_dir/../source/tlu/tlu_master.vhd"]"\
 "[file normalize "$origin_dir/../source/iic/iic_master.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/fei4_fifo_wrapper.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/xlx_k7v7_reset.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/core_sources/xlx_k7v7_gbt_example_design.vhd"]"\
 "[file normalize "$origin_dir/../source/fei4/idelay2.vhd"]"\
 "[file normalize "$origin_dir/../source/fei4/idelay.vhd"]"\
 "[file normalize "$origin_dir/../source/fei4/fei4_dat_deser.vhd"]"\
 "[file normalize "$origin_dir/../source/fei4/fei4_data_extract.vhd"]"\
 "[file normalize "$origin_dir/../source/ccpd/pulse_gen_core.vhd"]"\
 "[file normalize "$origin_dir/../source/ccpd/ccpd_cfg_core.vhd"]"\
 "[file normalize "$origin_dir/../source/adc/freq_counter.vhd"]"\
 "[file normalize "$origin_dir/../source/adc/adc_lvds_receiver.vhd"]"\
 "[file normalize "$origin_dir/../../../ZC706_Projects/caribou_test/caribou_test.srcs/sources_1/new/fei4_rx2.vhd"]"\
 "[file normalize "$origin_dir/../../../ZC706_Projects/caribou_test/caribou_test.srcs/sources_1/bd/ps7/hdl/ps7_wrapper.vhd"]"\
 "[file normalize "$origin_dir/../source/tlu/tlu_simulator_wrapper.vhd"]"\
 "[file normalize "$origin_dir/../source/ipbus/iobus.vhd"]"\
 "[file normalize "$origin_dir/../source/ipbus/axi_lite_ipif.vhd"]"\
 "[file normalize "$origin_dir/../source/iic/iic_controller.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/gbt_fpga_wrapper.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/gbt_fpga_control_link.vhd"]"\
 "[file normalize "$origin_dir/../source/gbt_fpga/fei4_gbt_interface.vhd"]"\
 "[file normalize "$origin_dir/../source/fei4/fei4_rx.vhd"]"\
 "[file normalize "$origin_dir/../source/fei4/fei4b_config.vhd"]"\
 "[file normalize "$origin_dir/../source/ccpd/pulse_gen.vhd"]"\
 "[file normalize "$origin_dir/../source/ccpd/ccpd_cfg.vhd"]"\
 "[file normalize "$origin_dir/../source/axi_hp/axi_mburst1.vhd"]"\
 "[file normalize "$origin_dir/../source/axi_hp/axi_mburst.vhd"]"\
 "[file normalize "$origin_dir/../source/axi_hp/axi_data_gen.vhd"]"\
 "[file normalize "$origin_dir/../source/adc/ads5292_lvds_receiver.vhd"]"\
 "[file normalize "$origin_dir/../source/TOP.vhd"]"\
 "[file normalize "$origin_dir/../../../ZC706_Projects/caribou_test/caribou_test.srcs/sources_1/imports/caribou_test/archive_project_summary.txt"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../source/gbt_fpga/xlx_k7v7_gbt_bank_package.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/xlx_k7v7_gbt_banks_user_setup.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_bank_package.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/tx_dpram/xlx_k7v7_tx_dpram.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/tx_dpram/xlx_k7v7_tx_dpram.ngc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "NGC" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/rx_dpram/xlx_k7v7_rx_dpram.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/rx_dpram/xlx_k7v7_rx_dpram.ngc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "NGC" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_elpeval.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_sync_pulse.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_sync_block.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/xlx_k7v7_gbt_tx_gearbox_std_dpram.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_gearbox_std_rdwrctrl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_polydiv.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/xlx_k7v7_gbt_rx_gearbox_std_dpram.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_gearbox_std_rdctrl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_syndrom.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_rs2errcor.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_lmbddet.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_errlcpoly.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_chnsrch.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_tx_startup_fsm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_tx_manual_phase_align.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_std.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_rx_startup_fsm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_rx_manual_phase_align.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_latopt.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_gtx_auto_phase_align.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/mgt/mgt_latopt_bitslipctrl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_scrambler_21bit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_scrambler_16bit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_gearbox_std.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_gearbox_latopt.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_rsencode.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_intlver.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_gearbox_std.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_gearbox_latopt.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_framealigner_wraddr.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_framealigner_rightshift.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_framealigner_pattsearch.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_framealigner_bscounter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_descrambler_21bit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_descrambler_16bit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_rsdec.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_deintlver.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_mgt_std.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/mgt/xlx_k7v7_mgt_latopt.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_scrambler.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_gearbox.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx_encoder.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_status.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_gearbox.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_framealigner.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_descrambler.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx_decoder.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/xlx_k7v7_gbt_rx_frameclk_phalgnr_ctrl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/mgt/multi_gigabit_transceivers.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_tx/gbt_tx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_rx/gbt_rx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/gbt_rx_frameclk_phalgnr.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/gbt_pattern_matchflag.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/gbt_pattern_generator.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/gbt_pattern_checker.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/gbt_bank_reset.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/tx_pll/xlx_k7v7_tx_pll.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/gbt_bank.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/fei4/8b10_dec.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/tlu/tlu_master.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/iic/iic_master.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/fei4_fifo_wrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/xlx_k7v7_reset.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/core_sources/xlx_k7v7_gbt_example_design.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/fei4/idelay2.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/fei4/idelay.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/fei4/fei4_dat_deser.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/fei4/fei4_data_extract.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/ccpd/pulse_gen_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/ccpd/ccpd_cfg_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/adc/freq_counter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/adc/adc_lvds_receiver.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ZC706_Projects/caribou_test/caribou_test.srcs/sources_1/new/fei4_rx2.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ZC706_Projects/caribou_test/caribou_test.srcs/sources_1/bd/ps7/hdl/ps7_wrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/tlu/tlu_simulator_wrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/ipbus/iobus.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/ipbus/axi_lite_ipif.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/iic/iic_controller.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/gbt_fpga_wrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/gbt_fpga_control_link.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/gbt_fpga/fei4_gbt_interface.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/fei4/fei4_rx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/fei4/fei4b_config.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/ccpd/pulse_gen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/ccpd/ccpd_cfg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/axi_hp/axi_mburst1.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/axi_hp/axi_mburst.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/axi_hp/axi_data_gen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/adc/ads5292_lvds_receiver.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../source/TOP.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "TOP" $obj

# Create 'clk_wiz_0' fileset (if not found)
if {[string equal [get_filesets -quiet clk_wiz_0] ""]} {
  create_fileset -blockset clk_wiz_0
}

# Set 'clk_wiz_0' fileset object
set obj [get_filesets clk_wiz_0]
set files [list \
 "[file normalize "$origin_dir/../../../ZC706_Projects/caribou_test/caribou_test.srcs/sources_1/ip/clk_wiz_0_0/clk_wiz_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'clk_wiz_0' fileset file properties for remote files
# None

# Set 'clk_wiz_0' fileset file properties for local files
# None

# Set 'clk_wiz_0' fileset properties
set obj [get_filesets clk_wiz_0]
set_property "top" "clk_wiz_0" $obj

# Create 'axi_hp_fifo' fileset (if not found)
if {[string equal [get_filesets -quiet axi_hp_fifo] ""]} {
  create_fileset -blockset axi_hp_fifo
}

# Set 'axi_hp_fifo' fileset object
set obj [get_filesets axi_hp_fifo]
set files [list \
 "[file normalize "$origin_dir/../../../ZC706_Projects/caribou_test/caribou_test.srcs/sources_1/ip/axi_hp_fifo_0/axi_hp_fifo.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'axi_hp_fifo' fileset file properties for remote files
# None

# Set 'axi_hp_fifo' fileset file properties for local files
# None

# Set 'axi_hp_fifo' fileset properties
set obj [get_filesets axi_hp_fifo]
set_property "top" "axi_hp_fifo" $obj

# Create 'fifo_generator_0' fileset (if not found)
if {[string equal [get_filesets -quiet fifo_generator_0] ""]} {
  create_fileset -blockset fifo_generator_0
}

# Set 'fifo_generator_0' fileset object
set obj [get_filesets fifo_generator_0]
set files [list \
 "[file normalize "$origin_dir/../../../ZC706_Projects/caribou_test/caribou_test.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'fifo_generator_0' fileset file properties for remote files
# None

# Set 'fifo_generator_0' fileset file properties for local files
# None

# Set 'fifo_generator_0' fileset properties
set obj [get_filesets fifo_generator_0]
set_property "top" "fifo_generator_0" $obj

# Create 'vio_0' fileset (if not found)
if {[string equal [get_filesets -quiet vio_0] ""]} {
  create_fileset -blockset vio_0
}

# Set 'vio_0' fileset object
set obj [get_filesets vio_0]
set files [list \
 "[file normalize "$origin_dir/../source/ip/vio_0/vio_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'vio_0' fileset file properties for remote files
# None

# Set 'vio_0' fileset file properties for local files
# None

# Set 'vio_0' fileset properties
set obj [get_filesets vio_0]
set_property "top" "vio_0" $obj

# Create 'ila_0' fileset (if not found)
if {[string equal [get_filesets -quiet ila_0] ""]} {
  create_fileset -blockset ila_0
}

# Set 'ila_0' fileset object
set obj [get_filesets ila_0]
set files [list \
 "[file normalize "$origin_dir/../source/ip/ila_0/ila_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'ila_0' fileset file properties for remote files
# None

# Set 'ila_0' fileset file properties for local files
# None

# Set 'ila_0' fileset properties
set obj [get_filesets ila_0]
set_property "top" "ila_0" $obj

# Create 'fei4_data_fifo' fileset (if not found)
if {[string equal [get_filesets -quiet fei4_data_fifo] ""]} {
  create_fileset -blockset fei4_data_fifo
}

# Set 'fei4_data_fifo' fileset object
set obj [get_filesets fei4_data_fifo]
set files [list \
 "[file normalize "$origin_dir/../source/ip/fei4_data_fifo/fei4_data_fifo.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'fei4_data_fifo' fileset file properties for remote files
# None

# Set 'fei4_data_fifo' fileset file properties for local files
# None

# Set 'fei4_data_fifo' fileset properties
set obj [get_filesets fei4_data_fifo]
set_property "top" "fei4_data_fifo" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../constr/phy_cons.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../constr/phy_cons.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property "target_constrs_file" "[file normalize "$origin_dir/../constr/phy_cons.xdc"]" $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 "[file normalize "$origin_dir/../../../ZC706_Projects/caribou_test/caribou_test.srcs/sim_1/new/fei4_cfg_tb.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/../../../ZC706_Projects/caribou_test/caribou_test.srcs/sim_1/new/fei4_cfg_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "FEI4_CFG_TB" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7z045ffg900-2 -flow {Vivado Synthesis 2014} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2014" [get_runs synth_1]
}
set obj [get_runs synth_1]

# Create 'clk_wiz_0_synth_1' run (if not found)
if {[string equal [get_runs -quiet clk_wiz_0_synth_1] ""]} {
  create_run -name clk_wiz_0_synth_1 -part xc7z045ffg900-2 -flow {Vivado Synthesis 2014} -strategy "Vivado Synthesis Defaults" -constrset clk_wiz_0
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs clk_wiz_0_synth_1]
  set_property flow "Vivado Synthesis 2014" [get_runs clk_wiz_0_synth_1]
}
set obj [get_runs clk_wiz_0_synth_1]
set_property "constrset" "clk_wiz_0" $obj

# Create 'axi_hp_fifo_synth_1' run (if not found)
if {[string equal [get_runs -quiet axi_hp_fifo_synth_1] ""]} {
  create_run -name axi_hp_fifo_synth_1 -part xc7z045ffg900-2 -flow {Vivado Synthesis 2014} -strategy "Vivado Synthesis Defaults" -constrset axi_hp_fifo
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs axi_hp_fifo_synth_1]
  set_property flow "Vivado Synthesis 2014" [get_runs axi_hp_fifo_synth_1]
}
set obj [get_runs axi_hp_fifo_synth_1]
set_property "constrset" "axi_hp_fifo" $obj

# Create 'fifo_generator_0_synth_1' run (if not found)
if {[string equal [get_runs -quiet fifo_generator_0_synth_1] ""]} {
  create_run -name fifo_generator_0_synth_1 -part xc7z045ffg900-2 -flow {Vivado Synthesis 2014} -strategy "Vivado Synthesis Defaults" -constrset fifo_generator_0
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs fifo_generator_0_synth_1]
  set_property flow "Vivado Synthesis 2014" [get_runs fifo_generator_0_synth_1]
}
set obj [get_runs fifo_generator_0_synth_1]
set_property "constrset" "fifo_generator_0" $obj

# Create 'vio_0_synth_1' run (if not found)
if {[string equal [get_runs -quiet vio_0_synth_1] ""]} {
  create_run -name vio_0_synth_1 -part xc7z045ffg900-2 -flow {Vivado Synthesis 2014} -strategy "Vivado Synthesis Defaults" -constrset vio_0
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs vio_0_synth_1]
  set_property flow "Vivado Synthesis 2014" [get_runs vio_0_synth_1]
}
set obj [get_runs vio_0_synth_1]
set_property "constrset" "vio_0" $obj

# Create 'ila_0_synth_1' run (if not found)
if {[string equal [get_runs -quiet ila_0_synth_1] ""]} {
  create_run -name ila_0_synth_1 -part xc7z045ffg900-2 -flow {Vivado Synthesis 2014} -strategy "Vivado Synthesis Defaults" -constrset ila_0
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs ila_0_synth_1]
  set_property flow "Vivado Synthesis 2014" [get_runs ila_0_synth_1]
}
set obj [get_runs ila_0_synth_1]
set_property "constrset" "ila_0" $obj

# Create 'fei4_data_fifo_synth_1' run (if not found)
if {[string equal [get_runs -quiet fei4_data_fifo_synth_1] ""]} {
  create_run -name fei4_data_fifo_synth_1 -part xc7z045ffg900-2 -flow {Vivado Synthesis 2014} -strategy "Vivado Synthesis Defaults" -constrset fei4_data_fifo
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs fei4_data_fifo_synth_1]
  set_property flow "Vivado Synthesis 2014" [get_runs fei4_data_fifo_synth_1]
}
set obj [get_runs fei4_data_fifo_synth_1]
set_property "constrset" "fei4_data_fifo" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7z045ffg900-2 -flow {Vivado Implementation 2014} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2014" [get_runs impl_1]
}
set obj [get_runs impl_1]

# Create 'clk_wiz_0_impl_1' run (if not found)
if {[string equal [get_runs -quiet clk_wiz_0_impl_1] ""]} {
  create_run -name clk_wiz_0_impl_1 -part xc7z045ffg900-2 -flow {Vivado Implementation 2014} -strategy "Vivado Implementation Defaults" -constrset clk_wiz_0 -parent_run clk_wiz_0_synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs clk_wiz_0_impl_1]
  set_property flow "Vivado Implementation 2014" [get_runs clk_wiz_0_impl_1]
}
set obj [get_runs clk_wiz_0_impl_1]
set_property "constrset" "clk_wiz_0" $obj

# Create 'axi_hp_fifo_impl_1' run (if not found)
if {[string equal [get_runs -quiet axi_hp_fifo_impl_1] ""]} {
  create_run -name axi_hp_fifo_impl_1 -part xc7z045ffg900-2 -flow {Vivado Implementation 2014} -strategy "Vivado Implementation Defaults" -constrset axi_hp_fifo -parent_run axi_hp_fifo_synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs axi_hp_fifo_impl_1]
  set_property flow "Vivado Implementation 2014" [get_runs axi_hp_fifo_impl_1]
}
set obj [get_runs axi_hp_fifo_impl_1]
set_property "constrset" "axi_hp_fifo" $obj

# Create 'fifo_generator_0_impl_1' run (if not found)
if {[string equal [get_runs -quiet fifo_generator_0_impl_1] ""]} {
  create_run -name fifo_generator_0_impl_1 -part xc7z045ffg900-2 -flow {Vivado Implementation 2014} -strategy "Vivado Implementation Defaults" -constrset fifo_generator_0 -parent_run fifo_generator_0_synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs fifo_generator_0_impl_1]
  set_property flow "Vivado Implementation 2014" [get_runs fifo_generator_0_impl_1]
}
set obj [get_runs fifo_generator_0_impl_1]
set_property "constrset" "fifo_generator_0" $obj

# Create 'vio_0_impl_1' run (if not found)
if {[string equal [get_runs -quiet vio_0_impl_1] ""]} {
  create_run -name vio_0_impl_1 -part xc7z045ffg900-2 -flow {Vivado Implementation 2014} -strategy "Vivado Implementation Defaults" -constrset vio_0 -parent_run vio_0_synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs vio_0_impl_1]
  set_property flow "Vivado Implementation 2014" [get_runs vio_0_impl_1]
}
set obj [get_runs vio_0_impl_1]
set_property "constrset" "vio_0" $obj

# Create 'ila_0_impl_1' run (if not found)
if {[string equal [get_runs -quiet ila_0_impl_1] ""]} {
  create_run -name ila_0_impl_1 -part xc7z045ffg900-2 -flow {Vivado Implementation 2014} -strategy "Vivado Implementation Defaults" -constrset ila_0 -parent_run ila_0_synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs ila_0_impl_1]
  set_property flow "Vivado Implementation 2014" [get_runs ila_0_impl_1]
}
set obj [get_runs ila_0_impl_1]
set_property "constrset" "ila_0" $obj

# Create 'fei4_data_fifo_impl_1' run (if not found)
if {[string equal [get_runs -quiet fei4_data_fifo_impl_1] ""]} {
  create_run -name fei4_data_fifo_impl_1 -part xc7z045ffg900-2 -flow {Vivado Implementation 2014} -strategy "Vivado Implementation Defaults" -constrset fei4_data_fifo -parent_run fei4_data_fifo_synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs fei4_data_fifo_impl_1]
  set_property flow "Vivado Implementation 2014" [get_runs fei4_data_fifo_impl_1]
}
set obj [get_runs fei4_data_fifo_impl_1]
set_property "constrset" "fei4_data_fifo" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:caribou_test"
